services:
  # Database
  # using atlas
  # mongo:
  #   image: mongo:latest
  #   container_name: aicompliance_mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks: [web]

  # Database GUI (View at http://localhost:8081)
  mongo-express:
    image: mongo-express
    container_name: aicompliance_gui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks: [web]

  # Queue Service
  # replaced by sqs
  # redis:
  #   image: redis:alpine
  #   container_name: aicompliance_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks: [web]
  # âœ… Backend (DEV mode)
  backend:
    image: node:20-alpine
    container_name: aicompliance_backend
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    # ports:
    #   - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # 
      - WATCHPACK_POLLING=true   # 
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    # traefik
    networks: [web]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aicompliance-api.rule=Host(`api.sitesafe.local`)"
      - "traefik.http.routers.aicompliance-api.entrypoints=web"
      - "traefik.http.services.aicompliance-api.loadbalancer.server.port=3000"

  # replaced by lambda worker
  # worker:
  #   image: node:20-alpine
  #   container_name: aicompliance_worker
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: npx tsx src/workers/documentWorker.ts
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #     - mongo
  #   restart: unless-stopped
  #   networks: [web]
  frontend:
    
    image: node:20-alpine
    container_name: aicompliance_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    # ports:
    #   - "5173:5173"
    restart: unless-stopped
    # traefik
    networks: [web]
    environment:
      - CHOKIDAR_USEPOLLING=true # <--- Forces Vite to poll
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aicompliance-frontend.rule=Host(`sitesafe.local`)"
      - "traefik.http.routers.aicompliance-frontend.entrypoints=web"
      - "traefik.http.services.aicompliance-frontend.loadbalancer.server.port=5173"

volumes:
  mongo_data:

networks:
  web:
    external: true
