services:
  # Database
  mongo:
    image: mongo:latest
    container_name: aicompliance_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks: [web]

  # Database GUI (View at http://localhost:8081)
  mongo-express:
    image: mongo-express
    container_name: aicompliance_gui
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks: [web]

  # Queue Service (Required for Day 5)
  redis:
    image: redis:alpine
    container_name: aicompliance_redis
    restart: always
    networks: [web]
  # âœ… Backend (DEV mode)
  backend:
    image: node:20-alpine
    container_name: aicompliance_backend
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    # ports:
    #   - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    # traefik
    networks: [web]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aicompliance-api.rule=Host(`api.aicompliance.vanndavidteng.com`)"
      - "traefik.http.routers.aicompliance-api.entrypoints=web,websecure"
      - "traefik.http.routers.aicompliance-api.tls=true"
      - "traefik.http.routers.aicompliance-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.aicompliance-api.loadbalancer.server.port=3000"

  worker:
    image: node:20-alpine
    container_name: aicompliance_worker
    working_dir: /app
    volumes:
      - .:/app
    command: npx tsx src/workers/documentWorker.ts
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    restart: unless-stopped
    networks: [web]
  frontend:
    image: node:20-alpine
    container_name: aicompliance_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    # ports:
    #   - "5173:5173"
    restart: unless-stopped
    # traefik
    networks: [web]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aicompliance-frontend.rule=Host(`aicompliance.vanndavidteng.com`)"
      - "traefik.http.routers.aicompliance-frontend.entrypoints=web,websecure"
      - "traefik.http.routers.aicompliance-frontend.tls=true"
      - "traefik.http.routers.aicompliance-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.aicompliance-frontend.loadbalancer.server.port=5173"

volumes:
  mongo_data:

networks:
  web:
    external: true
